image: node:18

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci

build:
  stage: build
  script:
    - npm run build

deploy:
  stage: deploy
  script:
    - echo "👉 Add your deploy commands here (e.g., docker build & push)"
  only:
    - main